### ISSUE TITLE
Can I get/download vcf file with this library?

### ISSUE THREAD

**Issue by MrRookie2013** [thegrizzlylabs/sardine-android#11]
Hello,

I already use and connect to server and get the list resource from this library (Thank you). But right now I need to download the vcf file, is it possible to download it with this library? 

ps: because if I want to download with retrofit I need to set the setCredentials (returns 401 when tried).

**Comment by guillaume-tgl** [comment]
Yes, it should be possible, have you tried to use the `InputStream get(String url)` method from your Sardine client?

**Comment by MrRookie2013** [comment]
Ah yes, it's working now. I made a mistake not converting InputStream into String after i get the result.

Thank you. You saved my day. I'll close the issue now. 👍
