### ISSUE TITLE
Providing methods to set timeouts

### ISSUE THREAD

**Issue by NLLAPPS** [thegrizzlylabs/sardine-android#2]
Would it be possible to provide methods to set timeouts in OkHttpSardine.java? Large files might fail on slow networks. 

`OkHttpClient.Builder clientBuilder = new OkHttpClient.Builder();
        clientBuilder.connectTimeout(10000, TimeUnit.MILLISECONDS);
        clientBuilder.readTimeout(10000, TimeUnit.MILLISECONDS);
        clientBuilder.writeTimeout(10000, TimeUnit.MILLISECONDS);`

**Comment by bvirlet** [comment]
You're welcome to offer a pull request :)!

**Comment by NLLAPPS** [comment]
OkHttpSardine.java

` public void setTimeouts(long connect, long read, long write) {
        this.client = client.newBuilder()
                .connectTimeout(connect, TimeUnit.MILLISECONDS)
                .readTimeout(read, TimeUnit.MILLISECONDS)
                .writeTimeout(write, TimeUnit.MILLISECONDS).build();
    } `

**Comment by NLLAPPS** [comment]
However, (if I am correct) setCredentials should also call newClientBuilder instead of new OkHttpClient.Builder().authenticator(new BasicAuthenticator(username, password))

**Comment by guillaume-tgl** [comment]
You're right, there was an error in `setCredentials`. I've fixed it and added a constructor with a client as argument so that you can configure it as you want.

**Comment by NLLAPPS** [comment]
Oh, it wouldn't work :) as it extends Sardine
