### ISSUE TITLE
using DAV on local network through https fails

### ISSUE THREAD

**Issue by alexdiostia** [thegrizzlylabs/sardine-android#20]
Hi
i couldn't succeed yet to use the client locally, behind my home router using SSL

i solved my previous issues, but realize that i can't connect to my server (RPi connected to my home router), if i am connected with the home WiFi.
i can almost understand because the domain name is resolved to an external IP that the android client then cannot reach. 

i tried to connect with the android client to the local address directly (https://192.168.xxxxx), but it doesn't work (SSLPeerUnverifiedException: Hostname 192.168.xxxx). Then I read that SSL certificates cannot be generated for IP addresses...

On the other hand, mapping a webDAV from a Windows explorer works fine to connect to my local Apache server ... (ie even using a domain name https://domain.net, and over the local WiFi...)

is there a configuration of the client to overcome this  local network access issue ? 

Thanks!

**Comment by alexdiostia** [comment]
well, actually no. i'm using a Let's Encrypt SSL certificate
that works just fine over cellular

the connection to the domain name, but without SSL, seems to work. That doesn't solve the issue, but i could browse locally (relying on the wifi security :( )

**Comment by guillaume-tgl** [comment]
I won't be able to help much on this issue. It looks like this could be a question to the OkHttp folks as it's not specific to this repository or to WebDAV. Have you tried to use OkHttp only and do a regular PUT or GET request?

**Comment by alexdiostia** [comment]
thanks. I will close this while investigating. this doesn't reem related to this specific project
