### ISSUE TITLE
Using the Library Async

### ISSUE THREAD

**Issue by hauketoenjes** [thegrizzlylabs/sardine-android#24]
Hey,

because i want to use the Library in my Android App, it would be nice to have an async webdav client. Or how do you use the Library in Android? Do you build a wrapper on your own or is there a feature im missing?

**Comment by guillaume-tgl** [comment]
Indeed, you need to make the calls to this library in a background thread in your app, using for example [`AsyncTask`](https://developer.android.com/reference/android/os/AsyncTask) or [`Task`](https://github.com/BoltsFramework/Bolts-Android).
