### ISSUE TITLE
Exclude transitively xpp and stax

### ISSUE THREAD

**Issue by guillaume-tgl** [thegrizzlylabs/sardine-android#26]
When including the library in my app as a Gradle dependency, I have to exclude again xpp and stax, even though they are excluded in the `build.gradle` of this library. Otherwise I have Proguard warnings that some library classes depend on program classes.
When I include this library directly as a submodule, I don't have this issue.

Does anybody using this library have the same issue?

**Comment by hauketoenjes** [comment]
I do not exclude the mentioned libraries and dont get a warning when using the library. Probably another problem (project specific)? You got this Problem in other Projects too?

**Comment by mohammad-karam** [comment]
I think I have the same problem . 
I have used your library ,every thing was allright when I used Android 9,Api28 I didn't got any error .
but when I tried the same APK with Android 6.0.1 API 23 my App crashed immediatly.
I have delete proguard completly and tried again. it works fine.
can you tell me how I could exclude xpp and stax ? just to try this soultion . 
or to provide AAR file to be able to add the library locally without using Gradle 
coz I don't know how to include the library directly as submodule

**Comment by guillaume-tgl** [comment]
This is how I include sardine-android in my app:
```
implementation ('com.thegrizzlylabs.sardine-android:sardine-android:0.5') {
        exclude module: 'stax'
        exclude module: 'stax-api'
        exclude module: 'xpp3'
    }
```

**Comment by mohammad-karam** [comment]
Thanks alot , it works very well.
