### ISSUE TITLE
Proguard replacement R8 and xmlpull

### ISSUE THREAD

**Issue by NLLAPPS** [thegrizzlylabs/sardine-android#28]
Does library need to also add `exclude group: 'xmlpull', module: 'xmlpull'` to simpleframework:simple usage?

I have come across an [issue](https://stackoverflow.com/questions/16474904/proguard-with-android-java-lang-nosuchmethoderror-android-util-xml-asattribute) and [another similar one](https://stackoverflow.com/questions/54245963/enabling-r8-causes-android-view-inflateexception-error-inflating-class-textview ). AOSP team member's insight at https://issuetracker.google.com/issues/123054725#comment5

**Comment by guillaume-tgl** [comment]
Could you paste the exception you get with R8?

**Comment by NLLAPPS** [comment]
It does not create any errors but strips of some parts which causes crash in the app.
I have added the following rule

`-keep class org.xmlpull.v1.* {*;}
-dontwarn org.xmlpull.v1.**
-dontwarn javax.xml.namespace.**`


and it prints out

`AGPBI: {"kind":"warning","text":"Library class android.content.res.XmlResourceParser implements program class org.xmlpull.v1.XmlPullParser","sources":[{}],"tool":"R8"}
`

However, this is due to a library having it included as part of their dependent - according to issue tracker information

**Comment by guillaume-tgl** [comment]
You shouldn't have to add a mention to keep xmlpull as this dependency is already present in Android. Do you have more details about the crashes you see?

**Comment by dbof10** [comment]
what is the workaround here?

**Comment by BrightVan** [comment]
> You shouldn't have to add a mention to keep xmlpull as this dependency is already present in Android. Do you have more details about the crashes you see?

why not use the xml parser present in Android instead of simple-xml?

**Comment by guillaume-tgl** [comment]
> why not use the xml parser present in Android instead of simple-xml?

SimpleXML is more than a XML parser, it can also serialize and deserialize Java classes to XML. And SimpleXML uses the XML parser library present in Android (XPP).

**Comment by BrightVan** [comment]
> > why not use the xml parser present in Android instead of simple-xml?
> 
> SimpleXML is more than a XML parser, it can also serialize and deserialize Java classes to XML. And SimpleXML uses the XML parser library present in Android (XPP).

i see, thanks.so this is no need to set proguard rules?

**Comment by guillaume-tgl** [comment]
No, this shouldn't be needed. But let me know if you have trouble integrating it. The latest version 0.7 should be even easier to integrate as stax and xpp are automatically excluded from the dependencies.

**Comment by BrightVan** [comment]
> No, this shouldn't be needed. But let me know if you have trouble integrating it. The latest version 0.7 should be even easier to integrate as stax and xpp are automatically excluded from the dependencies.
i use a singleton sardineClient to reuse  and
i think we should add a clear method to clear the username-password info in memery when we destory a relative activity

**Comment by guillaume-tgl** [comment]
Could you open another issue for this?

**Comment by BrightVan** [comment]
> Could you open another issue for this?

ok ,sorry about this
