### ISSUE TITLE
exists fails

### ISSUE THREAD

**Issue by NLLAPPS** [thegrizzlylabs/sardine-android#3]
You get `com.thegrizzlylabs.sardineandroid.impl.SardineException: Unexpected response (403 Forbidden)` you use request to check if resource exists on (at least Synology) some devices.
I don't know the reason but probably due to Preemptive authentication

Please provide alternative way to check if resource exists, such as 

`  @Override
    public boolean exists(String url) throws IOException {
        List<DavResource> list = getResources(url);
        return list.size() > 0;
    }`

**Comment by NLLAPPS** [comment]
or, perhaps do a seconds request if 403 fails and call getResources(url)

**Comment by guillaume-tgl** [comment]
Can you try with my latest commit?

**Comment by NLLAPPS** [comment]
Thanks. Seems to be fixed
