### ISSUE TITLE
Support for Android 4.x

### ISSUE THREAD

**Issue by 3c71** [thegrizzlylabs/sardine-android#40]
I'm trying to use this library on an app with a minimum SDK of 14, and it appears to work fine, appart from one method in AuthenticationIntercepter, which only support API 19 and above:

To fix this I've added a special method to get UTF8 standard charset:

        @Override
        public Response intercept(Chain chain) throws IOException {
            Request request = chain.request()
                .newBuilder()
                .addHeader("Authorization", Credentials.basic(userName, password, standardUTF8()))
                .build();
            return chain.proceed(request);
        }

The method to get a standard charset is as follows:

        public static Charset standardUTF8()
        {
            if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.KITKAT)
            {
                return StandardCharsets.UTF_8;
            }
            else
            {
                //noinspection CharsetObjectCanBeUsed
                return Charset.forName("UTF-8");
            }
        }

**Comment by guillaume-tgl** [comment]
Great. Feel free to open a PR with this change so that we can review it.

**Comment by 3c71** [comment]
Opened my first PR, hope I've done it right? Don't have git on my windows PC, so I made the modifications from github.

**Comment by guillaume-tgl** [comment]
Fixed by #41
