### ISSUE TITLE
The access of Sardine inner okHttpClient

### ISSUE THREAD

**Issue by BrightVan** [thegrizzlylabs/sardine-android#47]
Sardine  contains a okhttpClient, but it is private. when i use a sington to reuse the sardine instance, if "isPreemptive "set TRUE, it will cause error at switch webdav server. i want to remove the interceptor, but i can not access the okhttpClient.

**Comment by BrightVan** [comment]
```
@Override
    public void setCredentials(String username, String password, boolean isPreemptive) {
        OkHttpClient.Builder builder = client.newBuilder();
        if (isPreemptive) {
            builder.addInterceptor(new AuthenticationInterceptor(username, password));
        } else {
            List<Interceptor> interceptors = builder.interceptors();
            for (Interceptor interceptor : interceptors) {
                if (interceptor instanceof AuthenticationInterceptor) {
                    interceptors.remove(interceptor);
                }
            }
            builder.authenticator(new BasicAuthenticator(username, password));
        }
        this.client = builder.build();
    }

    public void clearCredentials() {
        OkHttpClient.Builder builder = client.newBuilder();
        builder.authenticator(Authenticator.NONE);
        this.client = builder.build();
    }
```

**Comment by guillaume-tgl** [comment]
There's a constructor of `OkHttpSardine` which takes a `OkHttpClient` as parameter. Isn't this enough to manage the credentials yourself? 
See https://github.com/thegrizzlylabs/sardine-android/blob/master/src/main/java/com/thegrizzlylabs/sardineandroid/impl/OkHttpSardine.java#L76

**Comment by BrightVan** [comment]
> There's a constructor of `OkHttpSardine` which takes a `OkHttpClient` as parameter. Isn't this enough to manage the credentials yourself?
> See https://github.com/thegrizzlylabs/sardine-android/blob/master/src/main/java/com/thegrizzlylabs/sardineandroid/impl/OkHttpSardine.java#L76
the question is `client.newBuilder().build()` will create a new Object，the constructor's parameter `OkHttpClient` is just a init object, they are not same.anyway, i clone and custom the code  as i need.
