### ISSUE TITLE
Bintray is closing any plans to publish somewher else?

### ISSUE THREAD

**Issue by NLLAPPS** [thegrizzlylabs/sardine-android#54]
Hi, please see https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by guillaume-tgl** [comment]
I think I will migrate to JitPack (which is also free for open-source projects) as it seems quite complicated to publish to Maven Central. If someone has any experience with Maven Central, feel free to help :)

**Comment by guillaume-tgl** [comment]
The simplest I've found is to use JitPack. I've changed instructions on how to install the library: https://github.com/thegrizzlylabs/sardine-android/commit/91f5a55de41828f501f57546c6f6fd105f567fc8
