### ISSUE TITLE
Have you considered adding "ntlm" and "digest" authenticator?

### ISSUE THREAD

**Issue by liuzho** [thegrizzlylabs/sardine-android#56]
hi, friend:

Have you considered adding ntlm and digest authenticator?

**Comment by guillaume-tgl** [comment]
Authentication needs to be handled at the HTTP client level.
It doesn't seem like they will support NTLM one day but there are some examples: https://github.com/square/okhttp/issues/4429

And there's already a library supporting digest authentication: https://github.com/rburgst/okhttp-digest
