### ISSUE TITLE
My iOS

### ISSUE THREAD

**Issue by hmstorecenter-com** [thegrizzlylabs/sardine-android#63]
My Android System HM STORE CENTER GROUPS. Relise update Brand Company profile.

**Comment by hmstorecenter-com** [comment]
> My Android System HM STORE CENTER GROUPS. Relise update Brand Company profile. 



`Note: Don't follow if your phone devices is completely true report playback issue in going to check your Internet. Thsi end to end services . Play Center. 

Project Record:(1.0-0.00)
1. Test 1.1 `

**Comment by guillaume-tgl** [comment]
I'm not sure to understand your issue. Please reopen and provide a stacktrace if you're experiencing an error.
