### ISSUE TITLE
Collaborate with dav4jvm

### ISSUE THREAD

**Issue by stokito** [thegrizzlylabs/sardine-android#73]
The repo has a few open pull requests and seems like you don't have enough time to dedicate to the project.

There is another WebDAV library from DavX5 app 
https://github.com/bitfireAT/dav4jvm
It's mainly used for CalDAV but I'm not sure if it can be used for files.

It's actively maintained so maybe you can merge this library into it? Then it would be easier for a new developer to peek a library to start using WebDAV.
The open source is great because it makes collaboration easier but a fragmentation makes it more difficult.

Or maybe there are some architectural design differences? If yes can you pleas explain pros and cons.

CC @rt1shnik @kotori2 @3c71 @sung-eun

**Comment by guillaume-tgl** [comment]
I don't see any reason to sunset this project given that it's maintained from time to time and seems to have many users. Developers are free to use dav4jvm if it's more maintained or more adapted to their use case.
