### ISSUE TITLE
jitpack No read access to repo

### ISSUE THREAD

**Issue by tangshg** [thegrizzlylabs/sardine-android#75]
Hello, I am unable to add dependencies to the project and jitpack shows No read access to repo. Can you help me take a look?

![image](https://github.com/thegrizzlylabs/sardine-android/assets/37105296/b0a65f95-6028-493d-9270-18a70c09dede)

![image](https://github.com/thegrizzlylabs/sardine-android/assets/37105296/5e904336-e5cf-4189-aa71-619ee186c118)

**Comment by tangshg** [comment]
![image](https://github.com/thegrizzlylabs/sardine-android/assets/37105296/14a65719-b509-4de4-ae2d-c51ef194b9ce)
Other dependencies are possible

**Comment by guillaume-tgl** [comment]
The correct address is `com.github.thegrizzlylabs:sardine-android`, as explained in the README 
See the correct page on Jipack: https://jitpack.io/#com.github.thegrizzlylabs/sardine-android
